terraform-aws-modules/terraform-aws-apigateway-v2

- main.tf
the integration uri must not always be lambda
currently you would use "lambda_arn" attribute also for http-proxy integrations
-
changed it locally within the cached module and executed my terraform successfully
> fix: Integration URI is not always a lambda_arn

- main.tf
Integration method `ANY` is not supported. The reason you can't see it on the AWS Console is because it always defaults to `POST`.
The has nothing to do with the HTTP method used to call the API and is just how API Gateway calls the Lambda API (the handler will still receive the correct method).
Lambda proxy integrations were broken upon first deployment of our services, but worked as soon as they were edited and saved in the console (without making any changes). I investigated and realised that it's because an unsupported integration method was used and upon editing and saving the console automatically changed this to `POST`.
No
Currently used in production in the company where I work.
> fix: default API Gateway integration method

- CHANGELOG.md
- README.md
- examples/complete-http/README.md
- examples/complete-http/outputs.tf
- outputs.tf
the outputs this_apigatewayv2_target_domain_name and this_apigatewayv2_hosted_zone_id was added
to use a custom domain name with route 53
all ok!!!, 💯 
manual hard test with my own infraestructure
> New usefull outputs to use with route53

- README.md
- examples/complete-http/main.tf
- main.tf
Adds support for setting `authorization_type` and `authorizer_id` on the `aws_apigatewayv2_route` resource, like so:
```
integrations = {
"GET /some-route" = {
lambda_arn = module.some_function.this_lambda_function_arn
payload_format_version = "2.0"
authorization_type = "CUSTOM"
authorizer_id = aws_apigatewayv2_authorizer.some_authorizer.id 
}
}
```
This module is helpful but limited by the lack of support for custom authorizers. This commit isn't perfect - it requires you to create an `aws_apigatewayv2_authorizer` independently, and then reference the id, but it's also immediately useful. If this isn't sufficient to merge, please let me know what you'd like to see in a commit and I'll see if I can match those expectations.
Defaults are set to what `aws_apigatewayv2_route` expects …
> feat: support authorization_type and authorizer_id on routes

- .gitignore
- .pre-commit-config.yaml
- README.md
- examples/complete-http/README.md
- examples/vpc-link-http/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

- README.md
- examples/complete-http/README.md
- examples/complete-http/main.tf
- examples/complete-http/versions.tf
- examples/vpc-link-http/README.md
- examples/vpc-link-http/main.tf
- examples/vpc-link-http/versions.tf
- versions.tf
- bump min supported version due to types unsupported on current
- get static checks back to passing state
- no
- ci-cd static checks
> fix: bump min supported version due to types unsupported on current

- README.md
- main.tf
- versions.tf
Removing old workaround that is no longer needed.
The issue that this workaround resolves has been fixed in aws 3.3.0 and newer versions of terraform don't allow you to set lifecycle ignores for a property that isn't specified as far as I can tell. 
The error is:
```
Error: expected passthrough_behavior to be one of [WHEN_NO_MATCH NEVER WHEN_NO_TEMPLATES], got
```
The issue is:
https://github.com/terraform-providers/terraform-provider-aws/issues/11148#issuecomment-619160589
This update forces users to upgrade their version of the AWS provider from 2.59 to at least 3.3.0.
I have tested this locally.
> fix: Remove workaround related to passthrough_behavior for older providers

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- README.md
- examples/complete-http/README.md
- examples/vpc-link-http/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
> chore: update documentation and pin `terraform_docs` version to avoid future changes

- README.md
- examples/complete-http/main.tf
- main.tf
- variables.tf
Add support for default_route_settings, fixes #30.
Control throttling and metrics.
No
Examples updated, also applied on our own real world infra.
> feat: Add support for default_route_settings

- README.md
- outputs.tf
- versions.tf
When disabling the entire module by:
* Setting `create = false` 
* Not setting `create_api_domain_name = false`, the outputs cause a plan time error.
Error:
```
Error: Error in function call
on .terraform/modules/environment.maintenance.this.apigateway.this/outputs.tf line 70, in output "apigatewayv2_domain_name_target_domain_name":
70:   value       = var.create_api_domain_name ? lookup(tomap(element(element(concat(aws_apigatewayv2_domain_name.this.*.domain_name_configuration, [""]), 0), 0)), "target_domain_name", "") : ""
|----------------
| aws_apigatewayv2_domain_name.this is empty tuple
Call to function "element" failed: cannot read elements from string.
Error: Error in function call
on .terraform/modules/environment.maintenance.this.apigateway.this/outputs.tf line 75, in output …
```
> fix: Fixed output when create_api_domain_name is false

- main.tf
This change adds a lifecycle policy to the aws_apigatewayv2_integration to allow for more stable changes to existing resources.
If there is a terraform change replacing both an API Gateway Route and an API Gateway Integration, it can run into an issue where a VPC link is being destroyed as the old Gateway Route is being deleted. The error becomes:
`Cannot delete Integration because it is referenced by the following Routes with Ids:`
In the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment) for aws api_gateway_deployment, it suggests to use a lifecycle block to create_before_destroy, allowing for the VPC link to be connected to the new API Gateway Route before destroying the connection. This also prevents downtime between …
> Feat: Add create_before_destroy lifecycle to integration resources

- README.md
- examples/complete-http/README.md
- examples/complete-http/main.tf
- examples/complete-http/versions.tf
- main.tf
- versions.tf
Add support for "response_parameters" to an integration to allow modification of response headers.
It is not possible to set the "response_parameters" block on an integration using this module, which can be useful for setting security headers that get added to all API responses.
There are no breaking changes
> feat: Add support for response_parameters in integrations

- README.md
- examples/complete-http/main.tf
- main.tf
- outputs.tf
- variables.tf
Adding a new section `Authorizers` which allows anyone to create multiple authorisers of varying types.
We needed to add a JWT and OIDC Auth to our project API Gateway
Deployed into our own sandbox account and working great.
> feat: Added support for Authorizers

- examples/complete-http/main.tf
- main.tf
Make it possible to pass the authorization_scopes as a comma separated string on the integration level. Passing it as a set of string like the AWS resource expects makes the variable validation fail with a " attribute types must all match for conversion to map" as also described [here](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/issues/61) 
Due to missing documentation on the AWS provider the authorization_scopes parameter was being ignored. The docs have been updated as seen [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_route)
This fixes [issue](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/issues/66)
No. This is an optional parameter
> fix: Add support for passing authorization_scopes on routes with JWT authorizer

- main.tf
Add compatibility for authorizer_result_ttl_in_seconds option in aws_apigatewayv2_authorizer resource
Support for specifying ttl on authorisers was missing
No breaking changes
> feat: Added support for ttl in authorizer resource

- .pre-commit-config.yaml
- main.tf
Add the ability to pass `enable_simple_responses` and `authorizer_credentials_arn` to an `aws_apigatewayv2_authorizer`
Fixes #70
Matches functionality in underlying aws resource - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_authorizer#enable_simple_responses
N/A
> feat: Added enable_simple_responses and authorizer_credentials_arn to authorizers

- examples/complete-http/README.md
- examples/complete-http/versions.tf
- examples/vpc-link-http/README.md
- examples/vpc-link-http/versions.tf
Fixes #73
This is a major release that invalidates v1.9.0 (#72).
> feat!: Upgraded AWS provider to v4 everywhere

- README.md
- examples/complete-http/README.md
- examples/complete-http/main.tf
- examples/complete-http/outputs.tf
- outputs.tf
Added map of created API Gateway Authorisers to module outputs.
Required for referencing authorisers outside of module usage, as no provider data resource exists
None
> feat: Added API GW Authorizer IDs to outputs

- examples/complete-http/README.md
- examples/complete-http/main.tf
- main.tf
Enable route_settings in default stage
route_settings will override default_settings, So even I just want to set throttling_rate_limit on route "POST /test", I have to set the remaining variables to use default_route_settings values, otherwise it will be AWS default value not default_route_settings value. e.g detailed_metrics_enabled will become false.
- Enable route_settings and add only the route with at least one of the options:
data_trace_enabled, logging_level, throttling_burst_limit, throttling_rate_limit, detailed_metrics_enabled is not null
- set the remaining variables to use use default_route_settings values
#78 
No
I have tested and deployed to my company AWS environment.
> feat: Enable route_settings in default stage

- .github/workflows/lock.yml
- .github/workflows/pr-title.yml
- .github/workflows/pre-commit.yml
- .github/workflows/release.yml
- .github/workflows/stale-actions.yaml
- .pre-commit-config.yaml
- README.md
- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No
> fix: Update CI workflow versions to remove deprecated runtime warnings

- README.md
- Changed `identity_sources` in `authorizers` from a string to an array of strings in the [Usage](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2?tab=readme-ov-file#usage) section.
In the README file, the `identity_sources` field in the `authorizers` section of the Usage example was incorrectly listed as a string.
According to the [module's specifications](https://registry.terraform.io/modules/terraform-aws-modules/apigateway-v2/aws/latest#input_authorizers), `identity_sources` should be an array of strings.
Here is an image of the error encountered with the current documentation:
- No
> docs: Update README Usage section to reflect array format for identity_sources

- outputs.tf
Strip off the `wss://` prefix from the stage_domain_name output in the case of websocket api.  This should fix #117
We want to use a single Cloudfront domain for all our services (S3, API Gateway HTTP, API Gateway Websocket). In order to configure the Cloudfront Origin you need to pass in a domain name.  I noticed that this value was not being set correctly.
I don't believe anyone would be using the incorrect domain name for websocket.
I ran against the websocket example before and after the change to verify that `stage_domain_name` is set correctly.
> fix: Remove websocket prefix from domain name output

- README.md
- examples/complete-http/main.tf
- main.tf
- variables.tf
- wrappers/main.tf
Allow users to explicitly pass the name of the hosted zone they would like the domain to be created in.
This allows for use cases where the hosted zone is delegated from another account (e.g. `team-abc.acme.com`).
Within that hosted zone you might want to create another domain (`api.team-abc.acme.com`). This currently isn't possible because the module expects a hosted zone with the name as passed in `var.domain_name` to be present.
- Resolves #112
- Closes #120
None, if the parameter isn't passed we just look up the hosted zone based on the `stripped_domain_name` as before.
> feat: Allow hosted zone name to be passed in separately

- README.md
- examples/complete-http/README.md
- examples/complete-http/versions.tf
- examples/vpc-link-http/README.md
- examples/vpc-link-http/versions.tf
- examples/websocket/README.md
- examples/websocket/versions.tf
- main.tf
- variables.tf
- versions.tf
- wrappers/main.tf
- wrappers/versions.tf
Support `ip_address_type` for dualstack.
https://github.com/hashicorp/terraform-provider-aws/pull/42145
No.
> feat: Support `ip_address_type`

- outputs.tf
Fixed null value outputs for stage access logs CloudWatch log group
Fixing broken output values; the change is made in accordance with the resource relocation: https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/5d1548624b39145ead043794ae5762abb9aadb27/migrations.tf#L10-L13
None
> fix: Update stage_access_logs_cloudwatch_log_group outputs
